#! bin/bash

# If --silent flag is passed, then we will not print the output
if [[ "$1" == "--silent" ]]; then
  SILENT="> /dev/null 2>&1"
fi

# Use SILENT as a string to pass to docker-compose
eval $"$DOCKER_COMPOSE up -d $SILENT"