# pull official lts base image
FROM node:18-bullseye-slim

WORKDIR /srv/www/client

# Copy package.json, install packages
RUN apt update
COPY package.json .
RUN npm i

# Vite/Svelte
EXPOSE 1337
# Storybook
EXPOSE 6006
