# Generated by Django 4.0.10 on 2023-03-12 16:47

import account.lib.model_mixins
import core.lib.model_fields
import core.lib.model_mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'permissions': (('add_superuser', 'Can add superuser'), ('change_superuser', 'Can change superuser'), ('delete_superuser', 'Can delete superuser'), ('view_superuser', 'Can view superuser')),
                'abstract': False,
            },
            bases=(core.lib.model_mixins.HasUuidId, account.lib.model_mixins.IsEmailable, models.Model),
        ),
        migrations.CreateModel(
            name='IsRedeemable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('isredeemable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.isredeemable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(editable=False, max_length=254, unique=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('emailable_user', core.lib.model_fields.PolymorphicFK(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(core.lib.model_mixins.HasUuidId, 'account.isredeemable', models.Model),
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('hash', models.CharField(editable=False, max_length=128)),
                ('protected_user', core.lib.model_fields.PolymorphicFK(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'password',
                'verbose_name_plural': 'passwords',
                'abstract': False,
            },
            bases=(core.lib.model_mixins.HasUuidId, models.Model),
        ),
        migrations.CreateModel(
            name='RedeemableKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('redeemable_user', core.lib.model_fields.PolymorphicFK(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemable_keys', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('redeemable_email_address', core.lib.model_fields.PolymorphicFK(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemable_keys', to='account.emailaddress')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.lib.model_mixins.HasUuidId, models.Model),
        ),
    ]
