# Generated by Django 4.0.10 on 2023-03-12 17:24

import core.lib.model_fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='emailable_user',
            field=core.lib.model_fields.PolymorphicFK(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='password',
            name='protected_user',
            field=core.lib.model_fields.PolymorphicFK(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='redeemablekey',
            name='redeemable_email_address',
            field=core.lib.model_fields.PolymorphicFK(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemable_keys', to='account.emailaddress'),
        ),
        migrations.AlterField(
            model_name='redeemablekey',
            name='redeemable_user',
            field=core.lib.model_fields.PolymorphicFK(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemable_keys', to=settings.AUTH_USER_MODEL),
        ),
    ]
