# See https://pre-commit.com/hooks.html for more hooks
repos:
    # TODO: Add this back in
    # -   repo: local
    #     hooks:
    #     -   id: api:format:black
    #         name: api:format:black
    #         entry: .scripts/run
    #         args: ["api:format:black"]
    #         language: script
    #     -   id: api:format:isort
    #         name: api:format:isort
    #         entry: .scripts/run
    #         args: ["api:format:isort"]
    #         language: script

    -   repo: https://github.com/Lucas-C/pre-commit-hooks
        rev: v1.4.2
        hooks:
        -   id: forbid-tabs
        -   id: remove-tabs
            args: [--whitespaces-count, "4"]

    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.4.0
        hooks:
        -   id: no-commit-to-branch
            args: [
                --branch,
                main,
                --branch,
                master,
                --branch,
                develop,
                --branch,
                staging,
                --branch,
                production,
            ]
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-added-large-files
        -   id: debug-statements
            language_version: python3
        -   id: check-merge-conflict
        -   id: check-case-conflict
        -   id: check-json
        -   id: check-yaml
            exclude: ^(^node_modules/.*$|^package-lock.json$)
        -   id: pretty-format-json
            exclude: ^(^node_modules/.*$|^package-lock.json$)
            args: [--autofix, --indent, "4"]
        -   id: requirements-txt-fixer

    -   repo: https://github.com/lovesegfault/beautysh
        rev: v6.2.1
        hooks:
        -   id: beautysh

    -   repo: https://github.com/IamTheFij/docker-pre-commit
        rev: v2.1.1
        hooks:
        -   id: docker-compose-check
