# See https://pre-commit.com/hooks.html for more hooks
repos:

 -  repo: local
    hooks:
    -   id: format:api:black
        name: format:api:black
        entry: .scripts/run format:api:black
        language: script
    -   id: format:api:isort
        name: format:api:isort
        entry: .scripts/run format:api:isort
        language: script


# -   repo: https://github.com/psf/black
#     rev: 22.12.0
#     hooks:
#     -   id: black
#         files: ^api/

# -   repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v3.2.0
#     hooks:
#     -   id: trailing-whitespace
#     -   id: end-of-file-fixer
#     -   id: check-yaml
#     -   id: check-added-large-files
#     -   id: debug-statements
#         language_version: python3

# -   repo: https://github.com/PyCQA/flake8
#     rev: 3.9.2
#     hooks:
#     -   id: flake8
#         language_version: python3

# -   repo: https://github.com/asottile/reorder_python_imports
#     rev: v2.6.0
#     hooks:
#     -   id: reorder-python-imports
#         args: [--application-directories=.:src, --py36-plus]

# -   repo: https://github.com/asottile/pyupgrade
#     rev: v2.29.0
#     hooks:
#     -   id: pyupgrade
#         args: [--py36-plus]

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.910
#     hooks:
#     -   id: mypy
#         files: ^src/
#         args: []
