#!/bin/bash

source ../.scripts/base.sh

# Add API-specific commands here
declare -A COMMANDS=(
    ["help"]="show_help 'api'",
    ["serve"]="bash .scripts/serve.sh",
    ["shell"]="bash .scripts/shell.sh",
    ["test"]="bash .scripts/test.sh",
    ["migrate"]="bash .scripts/migrate.sh",
    ["cmd"]="bash .scripts/cmd.sh",
    ["pip"]="bash .scripts/pip.sh",
    ["format:black"]="bash .scripts/format_black.sh",
    ["format:isort"]="bash .scripts/format_isort.sh"
)

run_command $CMD
