#!/bin/bash

source .scripts/base.sh

# Add commands here
declare -A COMMANDS=(
    ["help"]="show_help 'Project'",
    ["docker:build"]="source .scripts/docker/get:compose.sh && bash .scripts/docker/build.sh",
    ["docker:up"]="source .scripts/docker/get:compose.sh && bash .scripts/docker/up.sh",
    ["docker:up:server"]="source .scripts/docker/get:compose.sh && bash .scripts/docker/up:server.sh",
    ["docker:down:dev"]="source .scripts/docker/get:compose.sh && bash .scripts/docker/down:dev.sh",
    ["api:format:black"]="source .scripts/docker/get:compose.sh && bash .scripts/docker/up:server.sh --silent && EXEC=\"bash /srv/www/api/.scripts/run format:black\" && $DOCKER_COMPOSE exec server $EXEC",
    ["api:format:isort"]="source .scripts/docker/get:compose.sh && bash .scripts/docker/up:server.sh --silent && EXEC=\"bash /srv/www/api/.scripts/run format:isort\" && $DOCKER_COMPOSE exec server $EXEC",
    ["client:format:lint"]="source .scripts/docker/get:compose.sh && bash .scripts/docker/up:dev.sh --silent && EXEC=\"bash /app/client/.scripts/run format:lint\" && $DOCKER_COMPOSE exec client $EXEC",
)

run_command $CMD
